inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

Layout/LineLength:
  Max: 330



AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/**/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'app/helpers/*'
  NewCops: enable
